# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10.x]
        os: [ubuntu-latest]

    steps:
     - name: Checkout
       uses: actions/checkout@master
     - name: use Node.js 10
       uses: actions/setup-nody@v1
       with:
        node-version: 10
     - name: npm install and build
       run:
         npm -i
         npm run dev
         npm start
       env:
        CI: true

jobs:    #Deploy
  delpoy:
    #   runs-on: ubuntu-latest
     - name: ssh deploy
       uses: easingthemes/ssh-deploy@v2.1.4
       with:
    # Private Key  私钥
        SSH_PRIVATE_KEY: secrets.TENCETN_CLOUD_SSH_PRIVATE_KEY
    # Remote host   远程主机
        REMOTE_HOST:  secrets.TENCETN_CLOUD_HOST
    # Remote user  远程主机登录用户
        REMOTE_USER: root
    # Remote port  远程主机登录端口
        REMOTE_PORT: 22
    # optional, default is 22
    # Source directory  源文件 目录
        SOURCE: . # optional, default is 
    # Target directory  目标目录
        TARGET: secrets.TENCETN_CLOUD_TARGET
    # optional, default is /home/REMOTE_USER/
    # Arguments to pass to rsync
    #ARGS: # optional, default is -rltgoDzvO
