# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
 
 
 
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    #runs-on: self-hosted
    
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10.x]
        os: [ubuntu-latest]
        #, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: sudo  npm i -g npminstall && npminstall
    - run: sudo  npm run ci
      env:
        CI: true
    - name: depoly
      env:
        SSH_PRIVATE_KEY: ${{ secreats.SERVER_SSH_KEY}}
        ARGS: ' -rltgoDzvo --delete'
        SOURCE: 'build/'
        REMOTE_HOST: ${{ secrets.TX_HOST }}
        REMOTE_USER: ${{ secrets.TX_USER }}
        TARGET: ${{ secrets.TX_TARGET }}
        
      
