# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i -g npminstall && npminstall
    - run: npm run ci
      env:
        CI: true

    #Deploy
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.0.8
      env:
        ssh_PRIVATE_KEY:${{secretes.T4_MR}}
        ARGS: "-avz --delete"
          REMOTE_HOST: ${{ secrets.47.114.114.202 }}
          REMOTE_USER: ${{ secrets.root}}
          REMOTE_PORT: ${{ secrets.T4_MR }}
          SOURCE: "dist/"
          TARGET: "/opt/DCpool"
