# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Dc-pool-cms-CI/.TENCETN_CLOUD_HOST
on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    #- run: rm -rf /etc/localtime && ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
    - run: sudo npm config set registry https://registry.npm.taobao.org
    - run: sudo npm install
    - run: sudo npm install
  # Delpoly
    - name: ssh deploy  
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
    # Private Key  私钥
        SSH_PRIVATE_KEY: ${{ secrets.PASSWD }}
    # Remote host   远程主机
        REMOTE_HOST: "111.231.20.180"
    # Remote user  远程主机登录用户
        REMOTE_USER: "root"
    # Remote port  远程主机登录端口
    #   REMOTE_PORT: 22
    # optional, default is 22
    # Source directory  源文件 目录
        SOURCE: "."
    # optional, default is 
    # Target directory  目标目录
        TARGET: ${{ secrets.TARGET }}
    # optional, default is /home/REMOTE_USER/
    # Arguments to pass to rsync
    #ARGS: # optional, default is -rltgoDzvO
  #   Run ssh command
    - name: docker build and docker run 
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: docker build -f /opt/DC_Pool_CMS/Dockerfile -t dcpool-cms-service:test2  
        host: "111.231.20.180"
        username: "root"
        privateKey: ${{ secrets.PASSWD }}

